permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: LIZHENG
  email: lizhenghn@gmail.com
  link: http://lizhenghn123.github.io/
  cnblogs: http://www.cnblogs.com/lizhenghn
  github: https://github.com/lizhenghn123

# 站点信息
title: CPPER
description: CPPER`s blog
url: http://lizhenghn123.github.io/
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/headlogo.png
favicon: /public/img/headlogo.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: http://lizhenghn123.github.io/

# disqus 设置
disqus:
  shortname: lizhenghn

# 主题设置，自动激活某个标签
active: 架构

# 首页除了最新文章外显示分类
cates: 
  - Linux
  - Dev

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档