#博文的固定链接
permalink: /:year/:month/:day/:title.html
#分页时每页博文数量
paginate: 10
#markdown: redcarpet
markdown:       kramdown
#highlighter:    rouge
#kramdown:
#  input:                     GFM
#  auto_ids:                  true
#  footnote_nr:               1
#  entity_output:             as_char
#  toc_levels:                1..6
#  smart_quotes:              lsquo,rsquo,ldquo,rdquo
#  enable_coderay:            false
#  hard_wrap:                 false
#  syntax_highlighter:        rouge
#  transliterated_header_ids: true
#  footnote_backlink:         "&#8617;&#xfe0e;"

# 作者信息
author: 
  name: lizhenghn@gmail.com
  email: lizhenghn@gmail.com
  link: http://cpper.info
  cnblogs: http://www.cnblogs.com/lizhenghn
  github: https://github.com/lizhenghn123

# 站点信息
title: cpper
description: cpper`s blog
url: http://cpper.info
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/headlogo.png
favicon: /public/img/headlogo.png

# google analytics 设置
ga:
  id: UA-72126618-1 
  url: cpper.info
  
#sitemap
#sitemap:
#  path: sitemap.txt
gems: [jekyll-paginate]
  
# disqus 设置
disqus:
  shortname: lizhenghn
  comments: true
  disqus_show_comment_count: true

# 主题设置，自动激活某个标签
active: 架构

# 首页除了最新文章外显示分类
cates: 
  - 开发

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档